version: "3.8"

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - net
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "18080:80" 
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html:/usr/share/nginx/html"
    depends_on:
      - webpan
    networks:
      - net
  webpan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webpan
    volumes:
      - ./webpan:/file
    ports:
      - "7090:7090"
    networks:
      - net
    depends_on:
      - mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6377:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - net

networks:
  net:
    name: webpan